package codegen

import (
	"fmt"
	"io"
	"strings"
	"unicode"

	"github.com/jrandolf/envgen/internal/model"
)

// GenerateGo writes a Go config package for the given schema.
func GenerateGo(w io.Writer, schema *model.SchemaFile, pkg string) error {
	hasSensitive := false
	hasNumeric := false
	for _, v := range schema.Vars {
		if v.Sensitive {
			hasSensitive = true
		}
		if v.Type == model.TypePort || v.Type == model.TypeNumber {
			hasNumeric = true
		}
	}

	fmt.Fprintf(w, "// Code generated by envgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", pkg)

	// Imports.
	fmt.Fprintf(w, "import (\n")
	fmt.Fprintf(w, "\t\"fmt\"\n")
	fmt.Fprintf(w, "\t\"os\"\n")
	if hasNumeric {
		fmt.Fprintf(w, "\t\"strconv\"\n")
	}
	fmt.Fprintf(w, "\t\"strings\"\n")
	fmt.Fprintf(w, ")\n\n")

	// Secret type.
	if hasSensitive {
		writeSecretType(w)
	}

	// Config struct.
	fmt.Fprintf(w, "// Config holds all environment configuration for this service.\n")
	fmt.Fprintf(w, "type Config struct {\n")
	for _, v := range schema.Vars {
		goName := envToGoName(v.Name)
		goType := goFieldType(v)
		if v.Docs != "" {
			fmt.Fprintf(w, "\t// %s\n", v.Docs)
		}
		fmt.Fprintf(w, "\t%s %s\n", goName, goType)
	}
	fmt.Fprintf(w, "}\n\n")

	// Load function.
	writeLoadFunc(w, schema)

	return nil
}

func writeSecretType(w io.Writer) {
	fmt.Fprintf(w, "// Secret wraps a sensitive string value, preventing accidental logging.\n")
	fmt.Fprintf(w, "type Secret struct {\n")
	fmt.Fprintf(w, "\tvalue string\n")
	fmt.Fprintf(w, "}\n\n")
	fmt.Fprintf(w, "// NewSecret creates a Secret from a plaintext string.\n")
	fmt.Fprintf(w, "func NewSecret(v string) Secret { return Secret{value: v} }\n\n")
	fmt.Fprintf(w, "// Expose returns the underlying plaintext value.\n")
	fmt.Fprintf(w, "func (s Secret) Expose() string { return s.value }\n\n")
	fmt.Fprintf(w, "// String returns a redacted placeholder.\n")
	fmt.Fprintf(w, "func (s Secret) String() string { return \"[REDACTED]\" }\n\n")
	fmt.Fprintf(w, "// GoString returns a redacted placeholder.\n")
	fmt.Fprintf(w, "func (s Secret) GoString() string { return \"Secret([REDACTED])\" }\n\n")
	fmt.Fprintf(w, "// MarshalText returns a redacted placeholder for JSON/text encoding.\n")
	fmt.Fprintf(w, "func (s Secret) MarshalText() ([]byte, error) { return []byte(\"[REDACTED]\"), nil }\n\n")
}

func writeLoadFunc(w io.Writer, schema *model.SchemaFile) {
	fmt.Fprintf(w, "// Load reads all configuration from environment variables.\n")
	fmt.Fprintf(w, "// It collects all validation errors before returning.\n")
	fmt.Fprintf(w, "func Load() (*Config, error) {\n")
	fmt.Fprintf(w, "\tvar errs []string\n")
	fmt.Fprintf(w, "\tcfg := &Config{}\n\n")

	for _, v := range schema.Vars {
		localName := envToLocalName(v.Name)
		goName := envToGoName(v.Name)

		if v.Required && !v.HasDefault {
			// Required, no default: must be set.
			fmt.Fprintf(w, "\t%s := os.Getenv(%q)\n", localName, v.Name)
			fmt.Fprintf(w, "\tif %s == \"\" {\n", localName)
			fmt.Fprintf(w, "\t\terrs = append(errs, \"%s is required\")\n", v.Name)
			fmt.Fprintf(w, "\t}\n")
		} else if v.HasDefault {
			// Has default: use fallback.
			fmt.Fprintf(w, "\t%s := os.Getenv(%q)\n", localName, v.Name)
			fmt.Fprintf(w, "\tif %s == \"\" {\n", localName)
			fmt.Fprintf(w, "\t\t%s = %q\n", localName, v.Default)
			fmt.Fprintf(w, "\t}\n")
		} else {
			// Optional, no default.
			fmt.Fprintf(w, "\t%s := os.Getenv(%q)\n", localName, v.Name)
		}

		// Type conversion and assignment.
		switch v.Type {
		case model.TypePort, model.TypeNumber:
			if !v.Required {
				// Optional numeric: only parse if non-empty.
				fmt.Fprintf(w, "\tif %s != \"\" {\n", localName)
				fmt.Fprintf(w, "\t\tv, err := strconv.Atoi(%s)\n", localName)
				fmt.Fprintf(w, "\t\tif err != nil {\n")
				fmt.Fprintf(w, "\t\t\terrs = append(errs, fmt.Sprintf(\"%s: invalid %s %%q\", %s))\n", v.Name, v.Type, localName)
				fmt.Fprintf(w, "\t\t} else {\n")
				fmt.Fprintf(w, "\t\t\tcfg.%s = v\n", goName)
				fmt.Fprintf(w, "\t\t}\n")
				fmt.Fprintf(w, "\t}\n")
			} else {
				fmt.Fprintf(w, "\tif %s != \"\" {\n", localName)
				fmt.Fprintf(w, "\t\tv, err := strconv.Atoi(%s)\n", localName)
				fmt.Fprintf(w, "\t\tif err != nil {\n")
				fmt.Fprintf(w, "\t\t\terrs = append(errs, fmt.Sprintf(\"%s: invalid %s %%q\", %s))\n", v.Name, v.Type, localName)
				fmt.Fprintf(w, "\t\t} else {\n")
				fmt.Fprintf(w, "\t\t\tcfg.%s = v\n", goName)
				fmt.Fprintf(w, "\t\t}\n")
				fmt.Fprintf(w, "\t}\n")
			}
		case model.TypeEnum:
			fmt.Fprintf(w, "\tswitch %s {\n", localName)
			fmt.Fprintf(w, "\tcase %s:\n", joinQuoted(v.EnumValues))
			fmt.Fprintf(w, "\t\tcfg.%s = %s\n", goName, localName)
			if v.Required {
				fmt.Fprintf(w, "\tcase \"\":\n")
				fmt.Fprintf(w, "\t\terrs = append(errs, \"%s is required\")\n", v.Name)
			}
			fmt.Fprintf(w, "\tdefault:\n")
			fmt.Fprintf(w, "\t\terrs = append(errs, fmt.Sprintf(\"%s: must be one of [%s], got %%q\", %s))\n",
				v.Name, strings.Join(v.EnumValues, ", "), localName)
			fmt.Fprintf(w, "\t}\n")
		default:
			// String types.
			if v.Sensitive {
				fmt.Fprintf(w, "\tcfg.%s = NewSecret(%s)\n", goName, localName)
			} else {
				fmt.Fprintf(w, "\tcfg.%s = %s\n", goName, localName)
			}
		}
		fmt.Fprintf(w, "\n")
	}

	fmt.Fprintf(w, "\tif len(errs) > 0 {\n")
	fmt.Fprintf(w, "\t\treturn nil, fmt.Errorf(\"config errors:\\n  %%s\", strings.Join(errs, \"\\n  \"))\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "\treturn cfg, nil\n")
	fmt.Fprintf(w, "}\n")
}

// envToGoName converts DATABASE_URL to DatabaseURL.
func envToGoName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Handle well-known acronyms.
		upper := strings.ToUpper(p)
		if isAcronym(upper) {
			b.WriteString(upper)
		} else {
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

// envToLocalName converts DATABASE_URL to databaseURL (camelCase).
// It lowercases the first "word" from the env var, keeping the rest in Go naming.
func envToLocalName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	if len(parts) == 0 {
		return ""
	}

	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		upper := strings.ToUpper(p)
		if i == 0 {
			// First word: always lowercase.
			b.WriteString(p)
		} else if isAcronym(upper) {
			b.WriteString(upper)
		} else {
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

func goFieldType(v model.VarDef) string {
	switch v.Type {
	case model.TypePort, model.TypeNumber:
		return "int"
	default:
		if v.Sensitive {
			return "Secret"
		}
		return "string"
	}
}

func isAcronym(s string) bool {
	acronyms := map[string]bool{
		"ID": true, "URL": true, "API": true, "HTTP": true,
		"HTTPS": true, "JWT": true, "JWKS": true, "DB": true,
		"SQL": true, "TLS": true, "SSL": true, "SSH": true,
		"IP": true, "TCP": true, "UDP": true, "DNS": true,
		"URI": true, "SMTP": true, "NATS": true, "CORS": true,
		"OTEL": true, "LLM": true, "HMAC": true,
		"CSRF": true, "OIDC": true, "RP": true, "GA": true,
	}
	return acronyms[s]
}

func joinQuoted(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}
