package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/jrandolf/envgen/internal/model"
)

// GeneratePython writes a Python config module for the given schema.
func GeneratePython(w io.Writer, schema *model.SchemaFile) error {
	hasSensitive := false
	for _, v := range schema.Vars {
		if v.Sensitive {
			hasSensitive = true
			break
		}
	}

	fmt.Fprintf(w, "# Code generated by envgen. DO NOT EDIT.\n")
	fmt.Fprintf(w, "# pyright: reportArgumentType=false\n\n")
	fmt.Fprintf(w, "from __future__ import annotations\n\n")
	fmt.Fprintf(w, "import os\n")
	fmt.Fprintf(w, "from dataclasses import dataclass\n")
	if hasSensitive {
		fmt.Fprintf(w, "\nfrom pydantic import SecretStr\n")
	}
	fmt.Fprintf(w, "\n\n")

	// Dataclass.
	fmt.Fprintf(w, "@dataclass(frozen=True)\n")
	fmt.Fprintf(w, "class Config:\n")

	// Fields: required first, then optional.
	required := make([]model.VarDef, 0)
	optional := make([]model.VarDef, 0)
	for _, v := range schema.Vars {
		if v.Required {
			required = append(required, v)
		} else {
			optional = append(optional, v)
		}
	}

	for _, v := range required {
		pyName := strings.ToLower(v.Name)
		pyType := pyFieldType(v, false)
		if v.Docs != "" {
			fmt.Fprintf(w, "    #: %s\n", v.Docs)
		}
		fmt.Fprintf(w, "    %s: %s\n", pyName, pyType)
	}
	for _, v := range optional {
		pyName := strings.ToLower(v.Name)
		pyType := pyFieldType(v, true)
		if v.Docs != "" {
			fmt.Fprintf(w, "    #: %s\n", v.Docs)
		}
		fmt.Fprintf(w, "    %s: %s = None\n", pyName, pyType)
	}

	fmt.Fprintf(w, "\n")

	// from_env classmethod.
	fmt.Fprintf(w, "    @classmethod\n")
	fmt.Fprintf(w, "    def from_env(cls) -> Config:\n")
	fmt.Fprintf(w, "        errors: list[str] = []\n\n")

	// Process all vars.
	allVars := append(required, optional...)
	for _, v := range allVars {
		pyName := strings.ToLower(v.Name)

		if !v.Required {
			// Optional: just get, None if absent.
			fmt.Fprintf(w, "        %s = os.environ.get(%q) or None\n", pyName, v.Name)
		} else if v.HasDefault {
			// Required with default.
			fmt.Fprintf(w, "        %s = os.environ.get(%q, %q)\n", pyName, v.Name, v.Default)
		} else {
			// Required, no default.
			fmt.Fprintf(w, "        %s = os.environ.get(%q)\n", pyName, v.Name)
			fmt.Fprintf(w, "        if not %s:\n", pyName)
			fmt.Fprintf(w, "            errors.append(%q)\n", v.Name+" is required")
		}

		// Type coercion for numeric types — use a separate _int variable for Pyright.
		if v.Type == model.TypePort || v.Type == model.TypeNumber {
			intName := pyName + "_int"
			fmt.Fprintf(w, "        %s: int | None = None\n", intName)
			fmt.Fprintf(w, "        if %s is not None:\n", pyName)
			fmt.Fprintf(w, "            try:\n")
			fmt.Fprintf(w, "                %s = int(%s)\n", intName, pyName)
			fmt.Fprintf(w, "            except ValueError:\n")
			fmt.Fprintf(w, "                errors.append(f\"%s: invalid %s {%s!r}\")\n", v.Name, v.Type, pyName)
		}

		// Enum validation.
		if v.Type == model.TypeEnum && len(v.EnumValues) > 0 {
			fmt.Fprintf(w, "        if %s is not None and %s not in {%s}:\n", pyName, pyName, joinPyQuoted(v.EnumValues))
			fmt.Fprintf(w, "            errors.append(f\"%s: must be one of [%s], got {%s!r}\")\n",
				v.Name, strings.Join(v.EnumValues, ", "), pyName)
		}

		fmt.Fprintf(w, "\n")
	}

	fmt.Fprintf(w, "        if errors:\n")
	fmt.Fprintf(w, "            raise ValueError(\"config errors:\\n  \" + \"\\n  \".join(errors))\n\n")

	// Return constructor — wrap sensitive strings in SecretStr, use _int for numerics.
	fmt.Fprintf(w, "        return cls(\n")
	for _, v := range allVars {
		pyName := strings.ToLower(v.Name)
		if v.Sensitive {
			fmt.Fprintf(w, "            %s=SecretStr(%s) if %s is not None else None,\n", pyName, pyName, pyName)
		} else if v.Type == model.TypePort || v.Type == model.TypeNumber {
			fmt.Fprintf(w, "            %s=%s,\n", pyName, pyName+"_int")
		} else {
			fmt.Fprintf(w, "            %s=%s,\n", pyName, pyName)
		}
	}
	fmt.Fprintf(w, "        )\n")

	return nil
}

func pyFieldType(v model.VarDef, optional bool) string {
	base := "str"
	if v.Type == model.TypePort || v.Type == model.TypeNumber {
		base = "int"
	} else if v.Sensitive {
		base = "SecretStr"
	}
	if optional {
		return base + " | None"
	}
	return base
}

func joinPyQuoted(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}
