package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/jrandolf/envgen/internal/model"
)

// GenerateRust writes a Rust config module for the given schema.
// Sensitive values use secrecy::SecretString, which redacts on Debug and
// requires ExposeSecret to access the underlying value.
func GenerateRust(w io.Writer, schema *model.SchemaFile) error {
	hasSensitive := false
	for _, v := range schema.Vars {
		if v.Sensitive {
			hasSensitive = true
			break
		}
	}

	fmt.Fprintf(w, "// Code generated by envgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "#![allow(dead_code, unused_mut, reason = \"generated config may include fields or mutable validation state unused by some schemas\")]\n\n")

	fmt.Fprintf(w, "use std::env;\n")
	if hasSensitive {
		fmt.Fprintf(w, "use secrecy::SecretString;\n")
	}
	fmt.Fprintf(w, "\n")

	writeRustConfigStruct(w, schema)
	writeRustLoadImpl(w, schema)

	return nil
}

func writeRustConfigStruct(w io.Writer, schema *model.SchemaFile) {
	fmt.Fprintf(w, "/// Holds all environment configuration for this service.\n")
	fmt.Fprintf(w, "#[derive(Debug)]\n")
	fmt.Fprintf(w, "pub struct Env {\n")
	for _, v := range schema.Vars {
		rustName := envToRustName(v.Name)
		rustType := rustFieldType(v)
		if v.Docs != "" {
			fmt.Fprintf(w, "    /// %s\n", v.Docs)
		}
		fmt.Fprintf(w, "    pub %s: %s,\n", rustName, rustType)
	}
	fmt.Fprintf(w, "}\n\n")
}

func writeRustLoadImpl(w io.Writer, schema *model.SchemaFile) {
	fmt.Fprintf(w, "impl Env {\n")
	fmt.Fprintf(w, "    pub fn from_env() -> Result<Env, String> {\n")
	fmt.Fprintf(w, "        let mut errors: Vec<String> = Vec::new();\n\n")

	for _, v := range schema.Vars {
		rustName := envToRustName(v.Name)

		switch v.Type {
		case model.TypePort, model.TypeNumber:
			writeRustNumericVar(w, v, rustName)
		case model.TypeEnum:
			writeRustEnumVar(w, v, rustName)
		default:
			writeRustStringVar(w, v, rustName)
		}

		fmt.Fprintf(w, "\n")
	}

	fmt.Fprintf(w, "        // Set SKIP_ENV_VALIDATION=1 to suppress validation errors (e.g. in tests).\n")
	fmt.Fprintf(w, "        if !errors.is_empty() && env::var(\"SKIP_ENV_VALIDATION\").unwrap_or_default().is_empty() {\n")
	fmt.Fprintf(w, "            return Err(format!(\"config errors:\\n  {}\", errors.join(\"\\n  \")));\n")
	fmt.Fprintf(w, "        }\n\n")

	fmt.Fprintf(w, "        Ok(Env {\n")
	for _, v := range schema.Vars {
		rustName := envToRustName(v.Name)
		writeRustConstructorField(w, v, rustName)
	}
	fmt.Fprintf(w, "        })\n")
	fmt.Fprintf(w, "    }\n")
	fmt.Fprintf(w, "}\n\n")
}

func writeRustStringVar(w io.Writer, v model.VarDef, rustName string) {
	if v.Required && !v.HasDefault {
		fmt.Fprintf(w, "        let %s = env::var(%q).unwrap_or_default();\n", rustName, v.Name)
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rustName)
		fmt.Fprintf(w, "            errors.push(\"%s is required\".to_string());\n", v.Name)
		fmt.Fprintf(w, "        }\n")
	} else if v.HasDefault {
		fmt.Fprintf(w, "        let mut %s = env::var(%q).unwrap_or_default();\n", rustName, v.Name)
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rustName)
		fmt.Fprintf(w, "            %s = %q.to_string();\n", rustName, v.Default)
		fmt.Fprintf(w, "        }\n")
	} else {
		fmt.Fprintf(w, "        let %s = env::var(%q).unwrap_or_default();\n", rustName, v.Name)
	}
}

func writeRustNumericVar(w io.Writer, v model.VarDef, rustName string) {
	rawName := rustName + "_raw"

	if v.Required && !v.HasDefault {
		fmt.Fprintf(w, "        let %s = env::var(%q).unwrap_or_default();\n", rawName, v.Name)
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rawName)
		fmt.Fprintf(w, "            errors.push(\"%s is required\".to_string());\n", v.Name)
		fmt.Fprintf(w, "        }\n")
	} else if v.HasDefault {
		fmt.Fprintf(w, "        let mut %s = env::var(%q).unwrap_or_default();\n", rawName, v.Name)
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rawName)
		fmt.Fprintf(w, "            %s = %q.to_string();\n", rawName, v.Default)
		fmt.Fprintf(w, "        }\n")
	} else {
		fmt.Fprintf(w, "        let %s = env::var(%q).unwrap_or_default();\n", rawName, v.Name)
	}

	if v.Required {
		fmt.Fprintf(w, "        let %s: i64 = if %s.is_empty() {\n", rustName, rawName)
		fmt.Fprintf(w, "            0\n")
		fmt.Fprintf(w, "        } else {\n")
		fmt.Fprintf(w, "            match %s.parse::<i64>() {\n", rawName)
		fmt.Fprintf(w, "                Ok(v) => v,\n")
		fmt.Fprintf(w, "                Err(_) => {\n")
		fmt.Fprintf(w, "                    errors.push(format!(\"%s: invalid %s {:?}\", %s));\n", v.Name, v.Type, rawName)
		fmt.Fprintf(w, "                    0\n")
		fmt.Fprintf(w, "                }\n")
		fmt.Fprintf(w, "            }\n")
		fmt.Fprintf(w, "        };\n")
	} else {
		fmt.Fprintf(w, "        let %s: Option<i64> = if %s.is_empty() {\n", rustName, rawName)
		fmt.Fprintf(w, "            None\n")
		fmt.Fprintf(w, "        } else {\n")
		fmt.Fprintf(w, "            match %s.parse::<i64>() {\n", rawName)
		fmt.Fprintf(w, "                Ok(v) => Some(v),\n")
		fmt.Fprintf(w, "                Err(_) => {\n")
		fmt.Fprintf(w, "                    errors.push(format!(\"%s: invalid %s {:?}\", %s));\n", v.Name, v.Type, rawName)
		fmt.Fprintf(w, "                    None\n")
		fmt.Fprintf(w, "                }\n")
		fmt.Fprintf(w, "            }\n")
		fmt.Fprintf(w, "        };\n")
	}
}

func writeRustEnumVar(w io.Writer, v model.VarDef, rustName string) {
	if v.HasDefault {
		fmt.Fprintf(w, "        let mut %s = env::var(%q).unwrap_or_default();\n", rustName, v.Name)
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rustName)
		fmt.Fprintf(w, "            %s = %q.to_string();\n", rustName, v.Default)
		fmt.Fprintf(w, "        }\n")
	} else {
		fmt.Fprintf(w, "        let %s = env::var(%q).unwrap_or_default();\n", rustName, v.Name)
	}

	if len(v.EnumValues) > 0 {
		quoted := make([]string, len(v.EnumValues))
		for i, val := range v.EnumValues {
			quoted[i] = fmt.Sprintf("%q", val)
		}
		arms := strings.Join(quoted, " | ")

		fmt.Fprintf(w, "        match %s.as_str() {\n", rustName)
		fmt.Fprintf(w, "            %s => {}\n", arms)
		if v.Required && !v.HasDefault {
			fmt.Fprintf(w, "            \"\" => errors.push(\"%s is required\".to_string()),\n", v.Name)
		}
		fmt.Fprintf(w, "            _ => errors.push(format!(\"%s: must be one of [%s], got {:?}\", %s)),\n",
			v.Name, strings.Join(v.EnumValues, ", "), rustName)
		fmt.Fprintf(w, "        }\n")
	} else if v.Required && !v.HasDefault {
		fmt.Fprintf(w, "        if %s.is_empty() {\n", rustName)
		fmt.Fprintf(w, "            errors.push(\"%s is required\".to_string());\n", v.Name)
		fmt.Fprintf(w, "        }\n")
	}
}

func writeRustConstructorField(w io.Writer, v model.VarDef, rustName string) {
	switch v.Type {
	case model.TypePort, model.TypeNumber:
		fmt.Fprintf(w, "            %s,\n", rustName)
	default:
		if v.Sensitive {
			if v.Required {
				fmt.Fprintf(w, "            %s: SecretString::from(%s),\n", rustName, rustName)
			} else {
				fmt.Fprintf(w, "            %s: if %s.is_empty() { None } else { Some(SecretString::from(%s)) },\n", rustName, rustName, rustName)
			}
		} else if !v.Required {
			fmt.Fprintf(w, "            %s: if %s.is_empty() { None } else { Some(%s) },\n", rustName, rustName, rustName)
		} else {
			fmt.Fprintf(w, "            %s,\n", rustName)
		}
	}
}

// envToRustName converts DATABASE_URL to database_url (snake_case).
func envToRustName(name string) string {
	return strings.ToLower(name)
}

func rustFieldType(v model.VarDef) string {
	switch v.Type {
	case model.TypePort, model.TypeNumber:
		if v.Required {
			return "i64"
		}
		return "Option<i64>"
	default:
		if v.Sensitive {
			if v.Required {
				return "SecretString"
			}
			return "Option<SecretString>"
		}
		if v.Required {
			return "String"
		}
		return "Option<String>"
	}
}
