package codegen

import (
	"fmt"
	"io"
	"strings"
	"unicode"

	"github.com/jrandolf/envgen/internal/model"
)

// GenerateTypeScript writes a TypeScript env module with a typed loadEnv() function.
// The output has zero dependencies and validates all environment variables at startup.
// Sensitive values are wrapped in a Secret class that redacts on toString/toJSON/inspect.
func GenerateTypeScript(w io.Writer, schema *model.SchemaFile) error {
	hasSensitive := false
	for _, v := range schema.Vars {
		if v.Sensitive {
			hasSensitive = true
			break
		}
	}

	fmt.Fprintf(w, "// Code generated by envgen. DO NOT EDIT.\n\n")

	// Secret class.
	if hasSensitive {
		writeTSSecretClass(w)
	}

	// Env interface.
	fmt.Fprintf(w, "export interface Env {\n")
	for _, v := range schema.Vars {
		if v.Docs != "" {
			if v.DocsURL != "" {
				fmt.Fprintf(w, "  /** %s — {@link %s} */\n", v.Docs, v.DocsURL)
			} else {
				fmt.Fprintf(w, "  /** %s */\n", v.Docs)
			}
		}
		tsName := envToTSName(v.Name)
		tsType := tsFieldType(v)
		if !v.Required {
			fmt.Fprintf(w, "  %s: %s | undefined;\n", tsName, tsType)
		} else {
			fmt.Fprintf(w, "  %s: %s;\n", tsName, tsType)
		}
	}
	fmt.Fprintf(w, "}\n\n")

	// loadEnv function.
	writeLoadEnvFunc(w, schema)

	return nil
}

func writeTSSecretClass(w io.Writer) {
	fmt.Fprintf(w, "/** Wraps a sensitive string, preventing accidental logging or serialization. */\n")
	fmt.Fprintf(w, "export class Secret {\n")
	fmt.Fprintf(w, "  readonly #value: string;\n\n")
	fmt.Fprintf(w, "  constructor(value: string) {\n")
	fmt.Fprintf(w, "    this.#value = value;\n")
	fmt.Fprintf(w, "  }\n\n")
	fmt.Fprintf(w, "  /** Returns the underlying plaintext value. */\n")
	fmt.Fprintf(w, "  expose(): string {\n")
	fmt.Fprintf(w, "    return this.#value;\n")
	fmt.Fprintf(w, "  }\n\n")
	fmt.Fprintf(w, "  toString(): string {\n")
	fmt.Fprintf(w, "    return \"[REDACTED]\";\n")
	fmt.Fprintf(w, "  }\n\n")
	fmt.Fprintf(w, "  toJSON(): string {\n")
	fmt.Fprintf(w, "    return \"[REDACTED]\";\n")
	fmt.Fprintf(w, "  }\n\n")
	fmt.Fprintf(w, "  [Symbol.for(\"nodejs.util.inspect.custom\")](): string {\n")
	fmt.Fprintf(w, "    return \"Secret([REDACTED])\";\n")
	fmt.Fprintf(w, "  }\n")
	fmt.Fprintf(w, "}\n\n")
}

func writeLoadEnvFunc(w io.Writer, schema *model.SchemaFile) {
	fmt.Fprintf(w, "export function loadEnv(): Env {\n")
	fmt.Fprintf(w, "  const errors: string[] = [];\n\n")

	for _, v := range schema.Vars {
		tsName := envToTSName(v.Name)

		switch v.Type {
		case model.TypePort, model.TypeNumber:
			writeTSNumericVar(w, v, tsName)
		case model.TypeEnum:
			writeTSEnumVar(w, v, tsName)
		default:
			writeTSStringVar(w, v, tsName)
		}

		fmt.Fprintf(w, "\n")
	}

	fmt.Fprintf(w, "  if (errors.length > 0) {\n")
	fmt.Fprintf(w, "    throw new Error(`config errors:\\n  ${errors.join(\"\\n  \")}`);\n")
	fmt.Fprintf(w, "  }\n\n")

	// Return object — wrap sensitive values in Secret.
	fmt.Fprintf(w, "  return {\n")
	for _, v := range schema.Vars {
		tsName := envToTSName(v.Name)
		if v.Sensitive {
			if !v.Required {
				fmt.Fprintf(w, "    %s: %s != null ? new Secret(%s) : undefined,\n", tsName, tsName, tsName)
			} else {
				fmt.Fprintf(w, "    %s: new Secret(%s),\n", tsName, tsName)
			}
		} else {
			fmt.Fprintf(w, "    %s,\n", tsName)
		}
	}
	fmt.Fprintf(w, "  };\n")
	fmt.Fprintf(w, "}\n")
}

func writeTSStringVar(w io.Writer, v model.VarDef, tsName string) {
	if v.Required && !v.HasDefault {
		fmt.Fprintf(w, "  const %s = process.env.%s ?? \"\";\n", tsName, v.Name)
		fmt.Fprintf(w, "  if (!%s) {\n", tsName)
		fmt.Fprintf(w, "    errors.push(\"%s is required\");\n", v.Name)
		fmt.Fprintf(w, "  }\n")
	} else if v.HasDefault {
		fmt.Fprintf(w, "  const %s = process.env.%s || %q;\n", tsName, v.Name, v.Default)
	} else {
		// Optional, no default.
		fmt.Fprintf(w, "  const %s = process.env.%s || undefined;\n", tsName, v.Name)
	}
}

func writeTSNumericVar(w io.Writer, v model.VarDef, tsName string) {
	if v.HasDefault {
		fmt.Fprintf(w, "  const %sRaw = process.env.%s || %q;\n", tsName, v.Name, v.Default)
	} else if v.Required {
		fmt.Fprintf(w, "  const %sRaw = process.env.%s ?? \"\";\n", tsName, v.Name)
		fmt.Fprintf(w, "  if (!%sRaw) {\n", tsName)
		fmt.Fprintf(w, "    errors.push(\"%s is required\");\n", v.Name)
		fmt.Fprintf(w, "  }\n")
	} else {
		fmt.Fprintf(w, "  const %sRaw = process.env.%s;\n", tsName, v.Name)
	}

	if !v.Required {
		fmt.Fprintf(w, "  let %s: number | undefined = undefined;\n", tsName)
		fmt.Fprintf(w, "  if (%sRaw) {\n", tsName)
		fmt.Fprintf(w, "    const parsed = parseInt(%sRaw, 10);\n", tsName)
		fmt.Fprintf(w, "    if (isNaN(parsed)) {\n")
		fmt.Fprintf(w, "      errors.push(`%s: invalid %s \"${%sRaw}\"`);\n", v.Name, v.Type, tsName)
		fmt.Fprintf(w, "    } else {\n")
		fmt.Fprintf(w, "      %s = parsed;\n", tsName)
		fmt.Fprintf(w, "    }\n")
		fmt.Fprintf(w, "  }\n")
	} else {
		fmt.Fprintf(w, "  let %s = 0;\n", tsName)
		fmt.Fprintf(w, "  if (%sRaw) {\n", tsName)
		fmt.Fprintf(w, "    const parsed = parseInt(%sRaw, 10);\n", tsName)
		fmt.Fprintf(w, "    if (isNaN(parsed)) {\n")
		fmt.Fprintf(w, "      errors.push(`%s: invalid %s \"${%sRaw}\"`);\n", v.Name, v.Type, tsName)
		fmt.Fprintf(w, "    } else {\n")
		fmt.Fprintf(w, "      %s = parsed;\n", tsName)
		fmt.Fprintf(w, "    }\n")
		fmt.Fprintf(w, "  }\n")
	}
}

func writeTSEnumVar(w io.Writer, v model.VarDef, tsName string) {
	if v.Required && !v.HasDefault {
		fmt.Fprintf(w, "  const %s = process.env.%s ?? \"\";\n", tsName, v.Name)
		fmt.Fprintf(w, "  if (!%s) {\n", tsName)
		fmt.Fprintf(w, "    errors.push(\"%s is required\");\n", v.Name)
		fmt.Fprintf(w, "  }\n")
	} else if v.HasDefault {
		fmt.Fprintf(w, "  const %s = process.env.%s || %q;\n", tsName, v.Name, v.Default)
	} else {
		fmt.Fprintf(w, "  const %s = process.env.%s || undefined;\n", tsName, v.Name)
	}

	if len(v.EnumValues) > 0 {
		validSet := joinTSQuoted(v.EnumValues)
		fmt.Fprintf(w, "  if (%s && ![%s].includes(%s)) {\n", tsName, validSet, tsName)
		fmt.Fprintf(w, "    errors.push(`%s: must be one of [%s], got \"${%s}\"`);\n",
			v.Name, strings.Join(v.EnumValues, ", "), tsName)
		fmt.Fprintf(w, "  }\n")
	}
}

// envToTSName converts DATABASE_URL to databaseUrl (camelCase).
func envToTSName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	if len(parts) == 0 {
		return ""
	}
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		if i == 0 {
			b.WriteString(p)
		} else {
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

func tsFieldType(v model.VarDef) string {
	switch v.Type {
	case model.TypePort, model.TypeNumber:
		return "number"
	case model.TypeEnum:
		if len(v.EnumValues) > 0 {
			quoted := make([]string, len(v.EnumValues))
			for i, val := range v.EnumValues {
				quoted[i] = fmt.Sprintf("%q", val)
			}
			return strings.Join(quoted, " | ")
		}
		return "string"
	default:
		if v.Sensitive {
			return "Secret"
		}
		return "string"
	}
}

func joinTSQuoted(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}
